#!/usr/bin/env python3
"""Rotates images to one consistent pixel orientation.

The input may be one image file or a directory. Directories are searched
recursively and their relative structure is preserved below the output
directory. Pixel dimensions determine orientation: width greater than height
is landscape, while height greater than width is portrait. EXIF display
orientation is deliberately not used for this decision.

Examples::

    uv run scripts/rotate_images.py \
        --input ./images --output-dir ./landscape --target landscape

    uv run scripts/rotate_images.py \
        --input ./photo.jpg --output-dir ./portrait --target portrait
"""

from __future__ import annotations

import argparse
import logging
import shutil
import sys
from dataclasses import dataclass, fields
from pathlib import Path

from PIL import Image, UnidentifiedImageError

_LOGGER = logging.getLogger("rotate_images")

_DEFAULT_EXTENSIONS = (
    ".jpg",
    ".jpeg",
    ".png",
    ".bmp",
    ".tif",
    ".tiff",
    ".webp",
)
_ORIENTATIONS = ("landscape", "portrait")

# Common EXIF tags that become stale after rotating the pixel data.
_EXIF_ORIENTATION = 274
_EXIF_IMAGE_WIDTH = 256
_EXIF_IMAGE_HEIGHT = 257
_EXIF_PIXEL_X_DIMENSION = 40962
_EXIF_PIXEL_Y_DIMENSION = 40963


def orientation_for_size(width: int, height: int) -> str:
    """Returns the orientation represented by pixel dimensions.

    Args:
        width: Image width in pixels.
        height: Image height in pixels.

    Returns:
        ``landscape``, ``portrait`` or ``square``.
    """
    if width > height:
        return "landscape"
    if height > width:
        return "portrait"
    return "square"


def find_images(
    input_path: Path,
    output_dir: Path,
    extensions: tuple[str, ...],
) -> list[tuple[Path, Path]]:
    """Finds images and determines their output-relative paths.

    A file input is returned regardless of its extension so Pillow can decide
    whether it is a supported image. For a directory input, only configured
    extensions are included. A nested output directory is excluded to avoid
    processing files generated by an earlier run.

    Args:
        input_path: One source image or a directory to search recursively.
        output_dir: Output root to exclude from a directory scan.
        extensions: Accepted lower-case, dot-prefixed file extensions.

    Returns:
        Sorted ``(source, relative_output_path)`` pairs.
    """
    if input_path.is_file():
        return [(input_path, Path(input_path.name))]

    resolved_input = input_path.resolve()
    resolved_output = output_dir.resolve()
    output_is_nested = resolved_output.is_relative_to(resolved_input)
    found: list[tuple[Path, Path]] = []
    for path in sorted(input_path.rglob("*")):
        if not path.is_file() or path.suffix.lower() not in extensions:
            continue
        if output_is_nested and path.resolve().is_relative_to(resolved_output):
            continue
        found.append((path, path.relative_to(input_path)))
    return found


def _unique_output(
    target: Path, used: set[Path], on_exists: str
) -> Path | None:
    """Chooses an output path according to the collision policy.

    Args:
        target: Desired output path.
        used: Paths already reserved during this run.
        on_exists: ``suffix``, ``skip`` or ``overwrite``.

    Returns:
        The path to write, or None when an existing file should be skipped.
    """
    produced_this_run = target in used
    exists_on_disk = target.exists()

    if not produced_this_run:
        if not exists_on_disk:
            return target
        if on_exists == "overwrite":
            return target
        if on_exists == "skip":
            return None

    stem, suffix = target.stem, target.suffix
    number = 1
    while True:
        candidate = target.with_name(f"{stem}_{number}{suffix}")
        if candidate not in used and not candidate.exists():
            return candidate
        number += 1


def _save_rotated(image: Image.Image, target: Path, clockwise: bool) -> None:
    """Rotates loaded pixel data by 90 degrees and saves it.

    Args:
        image: Opened and fully loaded source image.
        target: Destination file path.
        clockwise: Whether to rotate clockwise instead of counterclockwise.
    """
    operation = (
        Image.Transpose.ROTATE_270
        if clockwise
        else Image.Transpose.ROTATE_90
    )
    rotated = image.transpose(operation)
    image_format = image.format
    if image_format is None:
        raise OSError("Pillow could not determine the source image format")
    rotated.format = image_format

    save_options: dict[str, object] = {}
    exif = image.getexif()
    if exif:
        exif[_EXIF_ORIENTATION] = 1
        for tag, value in (
            (_EXIF_IMAGE_WIDTH, rotated.width),
            (_EXIF_IMAGE_HEIGHT, rotated.height),
            (_EXIF_PIXEL_X_DIMENSION, rotated.width),
            (_EXIF_PIXEL_Y_DIMENSION, rotated.height),
        ):
            if tag in exif:
                exif[tag] = value
        save_options["exif"] = exif.tobytes()

    for key in ("icc_profile", "dpi"):
        if key in image.info:
            save_options[key] = image.info[key]

    if image_format == "JPEG":
        # Reuse the source JPEG's quality and chroma-subsampling settings.
        save_options["quality"] = "keep"
        save_options["subsampling"] = "keep"

    target.parent.mkdir(parents=True, exist_ok=True)
    rotated.save(target, format=image_format, **save_options)


@dataclass
class Stats:
    """Counters describing one run."""

    images_seen: int = 0
    landscape: int = 0
    portrait: int = 0
    square: int = 0
    rotated: int = 0
    copied: int = 0
    skipped_existing: int = 0
    read_errors: int = 0
    write_errors: int = 0

    def render(self) -> str:
        """Returns the counters as an indented summary."""
        return "\n".join(
            f"  {field.name:<18}: {getattr(self, field.name)}"
            for field in fields(self)
        )


def process_image(
    source: Path,
    target: Path,
    wanted: str,
    clockwise: bool,
    on_exists: str,
    dry_run: bool,
    used_outputs: set[Path],
    stats: Stats,
) -> None:
    """Copies or rotates one image into the output directory.

    Args:
        source: Source image path.
        target: Desired output path.
        wanted: Target orientation, ``landscape`` or ``portrait``.
        clockwise: Whether required rotations are clockwise.
        on_exists: Output collision policy.
        dry_run: If True, report actions without writing files.
        used_outputs: Paths already reserved during this run.
        stats: Counters updated in place.
    """
    stats.images_seen += 1
    try:
        with Image.open(source) as image:
            image.load()
            current = orientation_for_size(image.width, image.height)
            setattr(stats, current, getattr(stats, current) + 1)
            size = f"{image.width}x{image.height}"

            final = _unique_output(target, used_outputs, on_exists)
            if final is None:
                _LOGGER.info("Exists, skipping: %s", target)
                stats.skipped_existing += 1
                return
            if final.resolve() == source.resolve():
                _LOGGER.error("Output would overwrite its source: %s", source)
                stats.write_errors += 1
                return
            used_outputs.add(final)

            should_rotate = current != "square" and current != wanted
            action = "rotate" if should_rotate else "copy"
            if dry_run:
                _LOGGER.info(
                    "[dry-run] %s %s (%s) -> %s",
                    action, source, size, final,
                )
                if should_rotate:
                    stats.rotated += 1
                else:
                    stats.copied += 1
                return

            try:
                final.parent.mkdir(parents=True, exist_ok=True)
                if should_rotate:
                    _save_rotated(image, final, clockwise)
                    stats.rotated += 1
                else:
                    shutil.copy2(source, final)
                    stats.copied += 1
            except (OSError, ValueError) as exc:
                _LOGGER.warning("Failed to write %s: %s", final, exc)
                stats.write_errors += 1
                return

            _LOGGER.debug(
                "%s %s (%s) -> %s", action.capitalize(), source, size, final
            )
    except (UnidentifiedImageError, OSError) as exc:
        _LOGGER.warning("Failed to read image %s: %s", source, exc)
        stats.read_errors += 1


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Parses command-line arguments."""
    parser = argparse.ArgumentParser(
        description=(
            "Rotate images to one consistent orientation, determined from "
            "pixel width and height."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "-i", "--input", required=True, type=Path,
        help="One image file or a directory searched recursively.",
    )
    parser.add_argument(
        "-o", "--output-dir", required=True, type=Path,
        help="Output directory; recursive input structure is preserved.",
    )
    parser.add_argument(
        "-t", "--target", required=True, choices=_ORIENTATIONS,
        help="Orientation all non-square output images should have.",
    )
    parser.add_argument(
        "--rotation", choices=("clockwise", "counterclockwise"),
        default="clockwise",
        help="Direction used for required 90-degree rotations.",
    )
    parser.add_argument(
        "--ext", nargs="+", default=list(_DEFAULT_EXTENSIONS), metavar="EXT",
        help="Extensions included when the input is a directory.",
    )
    parser.add_argument(
        "--on-exists", choices=("suffix", "skip", "overwrite"),
        default="suffix", help="What to do when an output file exists.",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Inspect and report actions without writing files.",
    )
    parser.add_argument(
        "-v", "--verbose", action="store_true", help="Verbose (DEBUG) logging."
    )
    parser.add_argument(
        "-q", "--quiet", action="store_true", help="Only warnings and errors."
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """Rotates or copies every selected input image."""
    args = parse_args(argv)
    level = logging.INFO
    if args.verbose:
        level = logging.DEBUG
    elif args.quiet:
        level = logging.WARNING
    logging.basicConfig(level=level, format="%(levelname)s %(message)s")

    if not args.input.exists():
        _LOGGER.error("Input path does not exist: %s", args.input)
        return 2
    if not (args.input.is_file() or args.input.is_dir()):
        _LOGGER.error("Input is not a file or directory: %s", args.input)
        return 2
    if (
        args.input.is_dir()
        and args.input.resolve() == args.output_dir.resolve()
    ):
        _LOGGER.error("Input and output directories must be different")
        return 2

    extensions = tuple(
        value.lower() if value.startswith(".") else f".{value.lower()}"
        for value in args.ext
    )
    images = find_images(args.input, args.output_dir, extensions)
    if not images:
        _LOGGER.warning("No images found under %s", args.input)
        return 0
    _LOGGER.info("Found %d image(s) from %s", len(images), args.input)

    stats = Stats()
    used_outputs: set[Path] = set()
    for source, relative in images:
        process_image(
            source=source,
            target=args.output_dir / relative,
            wanted=args.target,
            clockwise=args.rotation == "clockwise",
            on_exists=args.on_exists,
            dry_run=args.dry_run,
            used_outputs=used_outputs,
            stats=stats,
        )

    _LOGGER.info(
        "Done%s. Summary:\n%s",
        " (dry-run)" if args.dry_run else "",
        stats.render(),
    )
    return 1 if stats.read_errors or stats.write_errors else 0


if __name__ == "__main__":
    sys.exit(main())
